"""Public component API.

Import components from here: ``from mikiui.components import Div, Button``.
Each component lives in its own module per ``context/project-structure.md`` and
is re-exported here for convenience.
"""

from __future__ import annotations

from .base import Component, component
from .html import (
    A,
    Abbr,
    Address,
    Article,
    Aside,
    Audio,
    Blockquote,
    Body,
    Br,
    Canvas,
    Code,
    Div,
    Dl,
    Dd,
    Dt,
    Em,
    Strong,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Head,
    Heading,
    Header,
    Footer,
    Hr,
    Html,
    Img,
    Kbd,
    Link,
    Li,
    Main,
    Mark,
    Menu,
    Meta,
    Nav,
    Ol,
    P,
    Pre,
    Script,
    Section,
    Small,
    Source,
    Span,
    Style,
    Svg,
    Time,
    Title,
    Ul,
    Video,
    Figure,
    Figcaption,
    Cite,
    Var,
    Samp,
)
from .button import Button, SubmitButton
from .picture import Picture
from .accordion import Accordion
from .tooltip import Tooltip
from .breadcrumbs import Breadcrumbs
from .menuitem import MenuItem
from .navbar import Navbar
from .input import Input, Textarea, Checkbox, Radio, Slider
from .form import Form, Label, Select, Option, Optgroup, Fieldset, Legend
from .table import Table, Caption, Thead, Tbody, Tfoot, Tr, Th, Td
from .dialog import Dialog, Details, Summary
from .modal import Modal
from .tabs import Tabs
from .progressbar import Progress, Meter, Output
from .treeview import TreeView
from .listview import ListView
from .calendar import Calendar
from .filepicker import FilePicker
from .chart import Chart

__all__ = [
    "Component",
    "component",
    "Html",
    "Head",
    "Title",
    "Meta",
    "Link",
    "Script",
    "Style",
    "Body",
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "Heading",
    "P",
    "Span",
    "Div",
    "Section",
    "Article",
    "Aside",
    "Header",
    "Footer",
    "Main",
    "Nav",
    "Br",
    "Hr",
    "Code",
    "Pre",
    "Blockquote",
    "Small",
    "Strong",
    "Em",
    "Mark",
    "Abbr",
    "Address",
    "Time",
    "Kbd",
    "A",
    "Ul",
    "Ol",
    "Li",
    "Dl",
    "Dt",
    "Dd",
    "Menu",
    "Img",
    "Video",
    "Audio",
    "Source",
    "Canvas",
    "Svg",
    "Figure",
    "Figcaption",
    "Cite",
    "Var",
    "Samp",
    "Button",
    "SubmitButton",
    "Input",
    "Textarea",
    "Checkbox",
    "Radio",
    "Slider",
    "Form",
    "Label",
    "Select",
    "Option",
    "Optgroup",
    "Fieldset",
    "Legend",
    "Table",
    "Caption",
    "Thead",
    "Tbody",
    "Tfoot",
    "Tr",
    "Th",
    "Td",
    "Dialog",
    "Details",
    "Summary",
    "Modal",
    "Tabs",
    "Progress",
    "Meter",
    "Output",
    "Navbar",
    "TreeView",
    "ListView",
    "Calendar",
    "FilePicker",
    "Chart",
    "Picture",
    "Accordion",
    "Tooltip",
    "Breadcrumbs",
    "MenuItem",
]
