"""Public component API.

Import components from here: ``from mikiui.components import Div, Button``.
Each component lives in its own module per ``context/project-structure.md`` and
is re-exported here for convenience.
"""

from __future__ import annotations

from .accordion import Accordion
from .base import Component, component
from .breadcrumbs import Breadcrumbs
from .button import Button, IconButton, SubmitButton
from .calendar import Calendar
from .chart import Chart
from .dialog import Details, Dialog, DialogBody, DialogFooter, DialogTitle, Summary
from .filepicker import FilePicker
from .form import Fieldset, Form, Label, Legend, Optgroup
from .html import (
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    SVG,
    A,
    Abbr,
    Abbreviation,
    Address,
    Anchor,
    Article,
    Aside,
    Audio,
    Blockquote,
    Body,
    Br,
    Canvas,
    Citation,
    Cite,
    Code,
    Dd,
    DescriptionDetail,
    DescriptionList,
    DescriptionTerm,
    Div,
    Dl,
    Dt,
    Em,
    Emphasis,
    Figcaption,
    Figure,
    Footer,
    Head,
    Header,
    Heading,
    Hr,
    Html,
    Image,
    Img,
    Kbd,
    Keyboard,
    Li,
    Link,
    ListItem,
    Main,
    Mark,
    Menu,
    Meta,
    Nav,
    Ol,
    OrderedList,
    P,
    Paragraph,
    Pre,
    Preformatted,
    Samp,
    Sample,
    Script,
    Section,
    Small,
    Source,
    Span,
    Strong,
    Style,
    Svg,
    Time,
    Title,
    Ul,
    UnorderedList,
    Var,
    Variable,
    Video,
)
from .input import Checkbox, Input, Option, Radio, Select, Slider, Switch, Textarea, Upload
from .listview import ListView
from .menuitem import MenuItem
from .modal import Modal
from .navbar import Navbar
from .picture import Picture
from .progressbar import Meter, Output, Progress, ProgressBar
from .splitview.splitview import EditorArea, EditorGroup, EditorTab
from .table import Caption, Table, Tbody, Td, Tfoot, Th, Thead, Tr
from .tabs import Tabs
from .tooltip import Tooltip
from .treeview import TreeView

__all__ = [
    "Component",
    "component",
    "Html",
    "Head",
    "Title",
    "Meta",
    "Link",
    "Script",
    "Style",
    "Body",
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "Heading",
    "P",
    "Paragraph",
    "Span",
    "Div",
    "Section",
    "Article",
    "Aside",
    "Header",
    "Footer",
    "Main",
    "Nav",
    "Br",
    "Hr",
    "Code",
    "Pre",
    "Preformatted",
    "Blockquote",
    "Small",
    "Strong",
    "Em",
    "Emphasis",
    "Mark",
    "Abbr",
    "Abbreviation",
    "Address",
    "Time",
    "Kbd",
    "Keyboard",
    "A",
    "Anchor",
    "Ul",
    "UnorderedList",
    "Ol",
    "OrderedList",
    "Li",
    "ListItem",
    "Dl",
    "DescriptionList",
    "Dt",
    "DescriptionTerm",
    "Dd",
    "DescriptionDetail",
    "Menu",
    "Img",
    "Image",
    "Video",
    "Audio",
    "Source",
    "Canvas",
    "Svg",
    "SVG",
    "Figure",
    "Figcaption",
    "Cite",
    "Citation",
    "Var",
    "Variable",
    "Samp",
    "Sample",
    "Button",
    "SubmitButton",
    "IconButton",
    "Input",
    "Textarea",
    "Checkbox",
    "Radio",
    "Slider",
    "Switch",
    "Upload",
    "Form",
    "Label",
    "Select",
    "Option",
    "Optgroup",
    "Fieldset",
    "Legend",
    "Table",
    "Caption",
    "Thead",
    "Tbody",
    "Tfoot",
    "Tr",
    "Th",
    "Td",
    "Dialog",
    "Details",
    "Summary",
    "DialogTitle",
    "DialogBody",
    "DialogFooter",
    "Modal",
    "Tabs",
    "Progress",
    "ProgressBar",
    "Meter",
    "Output",
    "Navbar",
    "TreeView",
    "ListView",
    "Calendar",
    "FilePicker",
    "Chart",
    "Picture",
    "Accordion",
    "EditorGroup",
    "EditorTab",
    "EditorArea",
    "Tooltip",
    "Breadcrumbs",
    "MenuItem",
]
