"""Project scaffolding for ``mikiui new``."""

from __future__ import annotations

from pathlib import Path

# -- UI framework options ----------------------------------------------------

UI_FRAMEWORKS: list[str] = ["tailwind", "bootstrap", "daisyui", "plain"]


def framework_config(framework: str) -> str:
    """Return the theme/config line to inject into the generated app.py."""
    return {
        "tailwind": 'app.set_theme("tailwind")\n',
        "bootstrap": 'app.set_theme("bootstrap")\n',
        "daisyui": (
            'app.set_theme("tailwind")  # DaisyUI works with Tailwind CSS\n'
        ),
        "plain": 'app.set_theme("light")\n',
    }.get(framework, 'app.set_theme("light")\n')


APP_TEMPLATE = '''"""MikiUI app generated by `mikiui new`.

Run `mikiui dev` for the dev server or `mikiui desktop` for a native window.
Themes: light, dark, solarized-dark, dracula.

UI Framework: {framework}
"""

from mikiui import MikiApp, Div, H1, P
from mikiui.components import A

app = MikiApp(title="{title}")
{config_line}

@app.route("/", title="{title}")
def home(ctx):
    return Div(
        Div(
            H1("{title}"),
            P("Edit app.py and run `mikiui dev`."),
            A("MikiUI docs", href="https://kilo.ai/docs"),
        ),
        class_="miki-container",
    )
'''

README_TEMPLATE = """# {title}

A MikiUI application using **{framework}** styling.

## Getting Started

```bash
mikiui dev        # Start the development server
mikiui desktop     # Open as a native desktop window
mikiui build       # Build for production
```

## Themes

Built-in themes: `light`, `dark`, `solarized-dark`, `dracula`.

```python
app.set_theme("dark")
```

## Switching Frameworks

You can change the CSS framework by editing `app.py` and changing the
`set_theme` call:

- `tailwind` — Tailwind CSS utility classes
- `bootstrap` — Bootstrap 5 component classes
- `daisyui` — DaisyUI component library (extends Tailwind)
- `plain` — No framework, just MikiUI default styles
"""

TAILWIND_CONFIG = """module.exports = {
  content: ["./app.py", "./mikiui/**/*.py"],
  theme: {
    extend: {},
  },
  plugins: [],
}
"""

POSTCSS_CONFIG = """module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
"""

REQUIREMENTS_TEMPLATE = """# MikiUI
mikiui
{rich_line}
"""


def scaffold(
    project_name: str,
    directory: str | None = None,
    framework: str = "tailwind",
) -> Path:
    """Create a new MikiUI project directory with a starter app.

    Parameters
    ----------
    project_name:
        The directory name (and app title) for the new project.
    directory:
        Parent directory (defaults to the current working directory).
    framework:
        CSS framework for scaffolded styling: ``tailwind``, ``bootstrap``,
        ``daisyui``, or ``plain``.
    """
    if framework not in UI_FRAMEWORKS:
        raise ValueError(
            f"Unknown framework '{framework}'. "
            f"Choose from: {', '.join(UI_FRAMEWORKS)}"
        )

    base = Path(directory) if directory else Path.cwd()
    target = base / project_name
    if target.exists():
        raise FileExistsError(f"{target} already exists")
    target.mkdir(parents=True)

    config_line = framework_config(framework)
    app_content = APP_TEMPLATE.format(
        title=project_name,
        framework=framework,
        config_line=config_line,
    )
    (target / "app.py").write_text(app_content, encoding="utf-8")

    (target / "README.md").write_text(
        README_TEMPLATE.format(title=project_name, framework=framework),
        encoding="utf-8",
    )

    # Tailwind/DaisyUI-specific: write tailwind.config.js and postcss.config.js
    if framework in ("tailwind", "daisyui"):
        (target / "tailwind.config.js").write_text(TAILWIND_CONFIG, encoding="utf-8")
        (target / "postcss.config.js").write_text(POSTCSS_CONFIG, encoding="utf-8")
        rich_line = "rich>=13.0"
    else:
        rich_line = ""
    (target / "requirements.txt").write_text(
        REQUIREMENTS_TEMPLATE.format(rich_line=rich_line),
        encoding="utf-8",
    )

    return target
