"""Project scaffolding for ``mikiui new``.

Uses the :class:`~mikiui.styling.system.StylingSystem` to set up the
styling framework during project creation, and prompts interactively for
the framework when not provided on the command line.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..styling import StylingSystem, normalize_framework

UI_FRAMEWORKS: list[str] = ["tailwind", "bootstrap", "daisyui", "plain"]

FRAMEWORK_DESCRIPTIONS: dict[str, str] = {
    "tailwind": "Tailwind CSS — utility-first, JIT compilation (requires Node.js)",
    "bootstrap": "Bootstrap 5 — CDN or local files + custom CSS",
    "plain": "Plain CSS — no framework, just your own styles",
}

APP_TEMPLATE = '''"""MikiUI app generated by `mikiui new`.

Run `mikiui dev` for the dev server or `mikiui desktop` for a native window.
Themes: light, dark, solarized-dark, dracula.

UI Framework: {framework}
"""

from mikiui import MikiApp, Div, H1, P
from mikiui.components import A

app = MikiApp(title="{title}")
{config_line}

@app.route("/", title="{title}")
def home(ctx):
    return Div(
        Div(
            H1("{title}"),
            P("Edit app.py and run `mikiui dev`."),
            A("MikiUI docs", href="https://kilo.ai/docs"),
        ),
        class_="miki-container",
    )
'''

README_TEMPLATE = """# {title}

A MikiUI application using **{framework}** styling.

## Getting Started

```bash
mikiui dev        # Start the development server
mikiui desktop     # Open as a native desktop window
mikiui build       # Build for production
```

## Themes

Built-in themes: `light`, `dark`, `solarized-dark`, `dracula`.

```python
app.set_theme("dark")
```

## Styling

This project uses **{framework}** for styling.

{framework_instructions}

## Switching Frameworks

You can change the CSS framework by editing `app.py` and changing the
`set_theme` call, or by running `mikiui install`:

- `mikiui install tailwind` — set up Tailwind CSS
- `mikiui install bootstrap` — use Bootstrap CDN
- `plain` — no framework, just custom CSS files
"""

REQUIREMENTS_TEMPLATE = """# MikiUI
mikiui
{rich_line}
"""


def framework_config(framework: str) -> str:
    """Return the theme/config line to inject into the generated app.py."""
    return {
        "tailwind": 'app.set_theme("tailwind")\n',
        "daisyui": 'app.set_theme("tailwind")\n',
        "bootstrap": 'app.set_theme("bootstrap")\n',
        "plain": 'app.set_theme("light")\n',
    }.get(framework, 'app.set_theme("light")\n')


def framework_readme_section(framework: str) -> str:
    """Return the styling section for the README."""
    sections = {
        "tailwind": """### Tailwind CSS

Tailwind CSS is configured automatically. DaisyUI is optional.

```bash
npm install          # Install Node.js dependencies (requires Node.js)
mikiui dev           # Start dev server (Tailwind auto-rebuilds CSS)
mikiui build --target web   # Build for production
```

To add DaisyUI, run:
```bash
mikiui install tailwind daisyui
```

To watch CSS changes during development, run in another terminal:
```bash
mikiui tailwind dev
```""",
        "daisyui": """### Tailwind CSS + DaisyUI

DaisyUI component library is enabled alongside Tailwind CSS.

```bash
npm install          # Install Node.js dependencies (requires Node.js)
mikiui dev           # Start dev server
mikiui tailwind dev  # Watch & rebuild CSS (in another terminal)
mikiui build --target web --daisyui  # Build for production
```""",
        "bootstrap": """### Bootstrap

Bootstrap is loaded from the jsDelivr CDN by default.

To use local Bootstrap files instead:
```bash
mikiui install bootstrap
```

Add your own custom CSS in `static/` and reference it in `app.py`:
```python
app.add_head_link("/static/my-styles.css", rel="stylesheet")
```""",
        "plain": """### Plain CSS

No CSS framework is used. Add your own CSS files in `static/` and
reference them in `app.py`:

```python
app.add_head_link("/static/styles.css", rel="stylesheet")
```""",
    }
    return sections.get(framework, sections.get("tailwind", ""))


def _prompt_framework() -> str:
    """Interactively prompt the user to choose a CSS framework.

    Returns
    -------
    str
        One of ``"tailwind"``, ``"bootstrap"``, ``"plain"``.
    """
    print("\nSelect a CSS framework for your MikiUI project:\n")
    for i, fw in enumerate(UI_FRAMEWORKS, start=1):
        desc = FRAMEWORK_DESCRIPTIONS.get(fw, "")
        print(f"  {i}. {fw:12s} — {desc}")
    print()

    while True:
        choice = input(f"Enter choice [1-{len(UI_FRAMEWORKS)}] (default: 1): ").strip()
        if not choice:
            return UI_FRAMEWORKS[0]
        try:
            idx = int(choice) - 1
            if 0 <= idx < len(UI_FRAMEWORKS):
                return UI_FRAMEWORKS[idx]
        except ValueError:
            pass
        print(f"  Please enter a number between 1 and {len(UI_FRAMEWORKS)}.")


def scaffold(
    project_name: str,
    directory: str | None = None,
    framework: str = "tailwind",
    *,
    interactive: bool = False,
    custom_css: list[str] | None = None,
) -> Path:
    """Create a new MikiUI project directory with a starter app.

    Parameters
    ----------
    project_name:
        The directory name (and app title) for the new project.
    directory:
        Parent directory (defaults to the current working directory).
    framework:
        CSS framework: ``"tailwind"``, ``"bootstrap"``, ``"plain"``.
    interactive:
        If ``True``, prompt the user to select a framework interactively.
    custom_css:
        Extra CSS file paths to add for Bootstrap/plain CSS projects.

    Returns
    -------
    Path
        Path to the created project directory.
    """
    if interactive and not framework:
        framework = _prompt_framework()

    if framework not in UI_FRAMEWORKS:
        raise ValueError(
            f"Unknown framework '{framework}'. "
            f"Choose from: {', '.join(UI_FRAMEWORKS)}"
        )

    base_fw, daisyui_enabled = normalize_framework(framework)
    effective_framework = base_fw

    base = Path(directory) if directory else Path.cwd()
    target = base / project_name
    if target.exists():
        raise FileExistsError(f"{target} already exists")
    target.mkdir(parents=True)

    config_line = framework_config(framework)
    app_content = APP_TEMPLATE.format(
        title=project_name,
        framework=framework,
        config_line=config_line,
    )
    (target / "app.py").write_text(app_content, encoding="utf-8")

    framework_instructions = framework_readme_section(framework)
    (target / "README.md").write_text(
        README_TEMPLATE.format(
            title=project_name,
            framework=framework,
            framework_instructions=framework_instructions,
        ),
        encoding="utf-8",
    )

    rich_line = "rich>=13.0" if effective_framework == "tailwind" else ""
    (target / "requirements.txt").write_text(
        REQUIREMENTS_TEMPLATE.format(rich_line=rich_line),
        encoding="utf-8",
    )

    custom_css = list(custom_css or [])
    ss = StylingSystem(project_dir=target)

    if effective_framework == "tailwind":
        (target / "tailwind.config.js").write_text(
            TAILWIND_CONFIG_TEMPLATE, encoding="utf-8"
        )
        (target / "postcss.config.js").write_text(
            POSTCSS_CONFIG_TEMPLATE, encoding="utf-8"
        )
        from ..styling.tailwind import write_config
        write_config(
            str(target / "tailwind.config.js"),
            theme="light",
            daisyui=daisyui_enabled,
        )
        ss.auto_setup(framework="tailwind", theme="light", daisyui=daisyui_enabled)

    elif effective_framework == "bootstrap":
        static_dir = target / "static"
        static_dir.mkdir(exist_ok=True)
        (static_dir / "custom.css").write_text(
            "/* Add your custom CSS here */\n", encoding="utf-8"
        )
        ss.auto_setup(
            framework="bootstrap",
            bootstrap_use_cdn=True,
            custom_css=["/static/custom.css"],
        )

    else:
        static_dir = target / "static"
        static_dir.mkdir(exist_ok=True)
        (static_dir / "styles.css").write_text(
            "/* Add your custom CSS here */\n", encoding="utf-8"
        )
        ss.auto_setup(
            framework="plain",
            custom_css=["/static/styles.css"],
        )

    (target / ".mikiui.json").write_text(
        json.dumps(
            {
                "framework": framework,
                "theme": "light",
                "styling": {
                    "framework": framework,
                    "theme": "light",
                },
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    return target


TAILWIND_CONFIG_TEMPLATE = """module.exports = {
  content: ["./app.py", "./mikiui/**/*.py"],
  theme: {
    extend: {},
  },
  plugins: [],
}
"""

POSTCSS_CONFIG_TEMPLATE = """module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
"""
