"""Project scaffolding for ``mikiui new``."""

from __future__ import annotations

import os
from pathlib import Path

APP_TEMPLATE = '''"""MikiUI app generated by `mikiui new`."""

from mikiui import MikiApp, Div, H1, P
from mikiui.components import A

app = MikiApp(title="{title}")

@app.route("/")
def home(ctx):
    return Div(
        H1("{title}"),
        P("Edit app.py and run `mikiui dev`."),
        A("MikiUI docs", href="https://kilo.ai/docs"),
    )
'''

README_TEMPLATE = "# {title}\n\nA MikiUI application. Run `mikiui dev` to start the dev server.\n"


def scaffold(project_name: str, directory: str | None = None) -> Path:
    """Create a new MikiUI project directory with a starter app."""
    base = Path(directory) if directory else Path.cwd()
    target = base / project_name
    if target.exists():
        raise FileExistsError(f"{target} already exists")
    target.mkdir(parents=True)
    (target / "app.py").write_text(APP_TEMPLATE.format(title=project_name), encoding="utf-8")
    (target / "README.md").write_text(README_TEMPLATE.format(title=project_name), encoding="utf-8")
    return target
